### PR TITLE
Some micro-optimizations

### PR DESCRIPTION
**Pull request by JarosLucky**
We do not need to process sequential arrays using pairs, because it is more efficient to do with ipairs.
We don't need to use heavy metatable strings, because it's faster to use string library functions
We don't need to create a new color every time if we can use an already created local color or a localized global color. Especially if we are sure that the color will never change in the future, through our fault.

### CODE REVIEW

**Comment by Cynosphere** [comment]
If you want to get into micro-optimization territory, you're better off just making a local variable of the color call, as global lookup isnt any better than creating a new color object. Plus bad code can easily mess up the color_white global and you wouldnt really want to rely on it.

**Comment by PotcFdk** [comment]
If we're nitpicking, then
- "better off just making a local variable of the color call"
-> might be true even in LuaJIT, but if it is at all, it's going to be not worth the trouble IMO
- "global lookup isnt any better than creating a new color object"
-> false; for reference, you can see how Color() is implemented [here](https://github.com/Facepunch/garrysmod/blob/d67fe85a3893be1ce73d424341dd54e418cb5cd3/garrysmod/lua/includes/util/color.lua#L14-L19)
- "bad code can easily mess up the color_white global"
-> bad code can literally break the entire game; I don't think this is a valid argument not to use something pre-existing or you can just stop using Garry's Mod altogether

**Comment by Earu** [comment]
- Having a local variable is way faster than accessing a global variable, (and yes even in LuaJIT), it's absolutely worth the trouble actually, you can get yourself an idea of how worth it is by bench marking it.
- Global lookup is better than creating a new color object, as it doesn't create new tables over and over in this case. So less garbage created over time.
- What's implied here is that anybody's code can override this global variable, and it's easily done as a mistake since this is not documented anywhere or at least I don't remember seeing it on the wiki.

**Comment by JarosLucky** [comment]
Okay, about the global variables, they are on the wiki and they are documented [there (Global Variables)](https://wiki.facepunch.com/gmod/Global_Variables).
I generally agree with the last two comments, almost to the last point. The truth is, "check that you have the error and not us."
And about replacing a variable and the fact that access to the local one is faster (which is true), it is solved very simply.

**Comment by JarosLucky** [comment]
If one of the developers claims that finding a global variable is worse than creating a new object.
Let him know that using metatable for a string is slower than using the string library.
That creating a completely new object by calling global functions and C-function cart along the way, i.e. knocking on the Lua API, is slower than making it once or using an already created object (i.e. color).
And what to use for consecutive numeric arrays pairs is slower than using ipairs.

**Comment by PotcFdk** [comment]
Has any of these optimizations even been tested? Optimizing without profiling is a waste of time.
Please post statistics about the speedups. When optimizations are primarily memory optimizations, it's fine to just compare, for example, how many new tables are being created. Not every optimization has to result in direct execution speedup, after all.

But so far, I've only seen random replacements without any _specific_ reasonings.
Ideally, you should be comparing multiple different alternatives.

One example: Don't just compare `pairs({...})` with `ipairs({...})`, but also compare it with `select(n, ...)` and other solutions. Benchmark it. Monitor how many new tables are being created and added to the table pool. Monitor how many new strings are being added to the string pool.

If you don't do that, what is the difference to just randomly replacing implementations with alternative implementations and then _hoping_ it will be faster?

**Comment by PotcFdk** [comment]
Closing for now. If anyone wants to work on this changeset, please start off by actually measuring the speedup or improvement in memory usage (especially creation of table/string garbage) compared to the current master branch before putting any more work into this. See https://github.com/Metastruct/EPOE/pull/7#issuecomment-668252298.

**Pull request closed without merging**
